name: brt_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  geocoding: ^2.1.1
  location: ^5.0.3
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  get: ^4.6.6
  intl_phone_field: ^3.2.0
  otp_text_field: ^1.1.3
  sqflite: ^2.3.2
  flutter_easyloading: ^3.0.3
  shared_preferences: ^2.0.13
  flutter_svg: ^2.0.6
  image_picker: ^0.8.4+4
  path: ^1.8.3
  # unique_identifier: # Remplacé par device_info_plus
  jiffy: 6.4.3
  http: ^1.1.0
  device_info_plus:
  flutter_localization:
  connectivity_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoapp.png"

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

